<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StudentsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('students')->delete();
        
        \DB::table('students')->insert(array (
            0 => 
            array (
                'id' => 2,
                'uid' => 'test',
                'name' => '学生甲',
                'sex' => '男',
                'phone' => '110120119',
                'sysid' => '96308564',
                'birth' => '2019-04-13',
                'minzu' => '畲',
                'jingji' => NULL,
                'hukou' => NULL,
                'jishu' => '0',
                'huji' => NULL,
                'xianzz' => NULL,
                'liushou' => 0,
                'liushouqk' => NULL,
                'liushoutgqk' => NULL,
                'biye' => '群英网络有限公司',
                'ganbu' => NULL,
                'huojiang' => NULL,
                'remember_token' => 'xuP9LtEUXb',
                'created_at' => '2013-03-30 09:17:26',
                'updated_at' => '2021-04-03 00:28:11',
            ),
            1 => 
            array (
                'id' => 3,
                'uid' => '11536946',
                'name' => '黎帅',
                'sex' => '男',
                'phone' => '13257950920',
                'sysid' => '23639283',
                'birth' => '1985-12-11',
                'minzu' => '畲',
                'jingji' => NULL,
                'hukou' => NULL,
                'jishu' => '0',
                'huji' => NULL,
                'xianzz' => NULL,
                'liushou' => 0,
                'liushouqk' => NULL,
                'liushoutgqk' => NULL,
                'biye' => '联软传媒有限公司',
                'ganbu' => NULL,
                'huojiang' => NULL,
                'remember_token' => 'shABRz7p2E',
                'created_at' => '2006-09-28 23:11:05',
                'updated_at' => '2008-09-23 05:41:03',
            ),
            2 => 
            array (
                'id' => 4,
                'uid' => '90460066',
                'name' => '凌晶',
                'sex' => '女',
                'phone' => '18137801518',
                'sysid' => '20798288',
                'birth' => '2000-02-02',
                'minzu' => '汉',
                'jingji' => NULL,
                'hukou' => NULL,
                'jishu' => '0',
                'huji' => NULL,
                'xianzz' => NULL,
                'liushou' => 0,
                'liushouqk' => NULL,
                'liushoutgqk' => NULL,
                'biye' => '维旺明科技有限公司',
                'ganbu' => NULL,
                'huojiang' => NULL,
                'remember_token' => 'auZS1mpyXT',
                'created_at' => '2012-02-19 09:17:25',
                'updated_at' => '1974-03-25 19:58:36',
            ),
            3 => 
            array (
                'id' => 5,
                'uid' => '42365184',
                'name' => '秦冰冰',
                'sex' => '男',
                'phone' => '13900316761',
                'sysid' => '87890951',
                'birth' => '1973-01-27',
                'minzu' => '畲',
                'jingji' => NULL,
                'hukou' => NULL,
                'jishu' => '0',
                'huji' => NULL,
                'xianzz' => NULL,
                'liushou' => 0,
                'liushouqk' => NULL,
                'liushoutgqk' => NULL,
                'biye' => '创亿网络有限公司',
                'ganbu' => NULL,
                'huojiang' => NULL,
                'remember_token' => 'BvRNJQ9aHo',
                'created_at' => '2007-05-03 08:22:12',
                'updated_at' => '1972-04-18 09:30:02',
            ),
            4 => 
            array (
                'id' => 6,
                'uid' => '97827816',
                'name' => '欧玉英',
                'sex' => '男',
                'phone' => '17767230472',
                'sysid' => '98366073',
                'birth' => '1997-08-17',
                'minzu' => '畲',
                'jingji' => NULL,
                'hukou' => NULL,
                'jishu' => '0',
                'huji' => NULL,
                'xianzz' => NULL,
                'liushou' => 0,
                'liushouqk' => NULL,
                'liushoutgqk' => NULL,
                'biye' => '飞利信信息有限公司',
                'ganbu' => NULL,
                'huojiang' => NULL,
                'remember_token' => 'Pu8moX1Do3',
                'created_at' => '1986-12-12 16:33:45',
                'updated_at' => '1979-04-17 17:56:59',
            ),
            5 => 
            array (
                'id' => 7,
                'uid' => '97452034',
                'name' => '窦成',
                'sex' => '男',
                'phone' => '17799603758',
                'sysid' => '14592028',
                'birth' => '2018-09-23',
                'minzu' => '汉',
                'jingji' => NULL,
                'hukou' => NULL,
                'jishu' => '0',
                'huji' => NULL,
                'xianzz' => NULL,
                'liushou' => 0,
                'liushouqk' => NULL,
                'liushoutgqk' => NULL,
                'biye' => '昂歌信息传媒有限公司',
                'ganbu' => NULL,
                'huojiang' => NULL,
                'remember_token' => 'KBYLJHOyER',
                'created_at' => '1972-04-19 20:05:45',
                'updated_at' => '2007-08-13 02:06:51',
            ),
            6 => 
            array (
                'id' => 8,
                'uid' => '34185498',
                'name' => '赵娜',
                'sex' => '女',
                'phone' => '17197588113',
                'sysid' => '96107232',
                'birth' => '1983-06-22',
                'minzu' => '畲',
                'jingji' => NULL,
                'hukou' => NULL,
                'jishu' => '0',
                'huji' => NULL,
                'xianzz' => NULL,
                'liushou' => 0,
                'liushouqk' => NULL,
                'liushoutgqk' => NULL,
                'biye' => '双敏电子信息有限公司',
                'ganbu' => NULL,
                'huojiang' => NULL,
                'remember_token' => 'elc4Vcyu8K',
                'created_at' => '1989-03-10 12:26:16',
                'updated_at' => '1988-12-29 20:13:34',
            ),
            7 => 
            array (
                'id' => 9,
                'uid' => '21983497',
                'name' => '项坤',
                'sex' => '男',
                'phone' => '15641596350',
                'sysid' => '84329003',
                'birth' => '2010-03-10',
                'minzu' => '汉',
                'jingji' => NULL,
                'hukou' => NULL,
                'jishu' => '0',
                'huji' => NULL,
                'xianzz' => NULL,
                'liushou' => 0,
                'liushouqk' => NULL,
                'liushoutgqk' => NULL,
                'biye' => '信诚致远科技有限公司',
                'ganbu' => NULL,
                'huojiang' => NULL,
                'remember_token' => '4a4dENCqwV',
                'created_at' => '1993-04-29 22:33:00',
                'updated_at' => '1984-05-20 13:52:09',
            ),
            8 => 
            array (
                'id' => 10,
                'uid' => '94395183',
                'name' => '靳哲',
                'sex' => '女',
                'phone' => '15107678894',
                'sysid' => '66133427',
                'birth' => '1991-04-23',
                'minzu' => '汉',
                'jingji' => NULL,
                'hukou' => NULL,
                'jishu' => '0',
                'huji' => NULL,
                'xianzz' => NULL,
                'liushou' => 0,
                'liushouqk' => NULL,
                'liushoutgqk' => NULL,
                'biye' => '华泰通安传媒有限公司',
                'ganbu' => NULL,
                'huojiang' => NULL,
                'remember_token' => 'hGR7R3uenL',
                'created_at' => '2007-01-17 09:36:43',
                'updated_at' => '2016-11-27 20:25:14',
            ),
        ));
        
        
    }
}